### ISSUE TITLE
Get rid of Zalgo in browser dev tools

### ISSUE THREAD

**Issue by andrewblond** [enb-bem/enb-magic-platform#37]

**Comment by andrewblond** [comment]
Resolved in 412c12a6e6b4d2a6a230ddcabdd815c8ea37a749

**Comment by tadatuta** [comment]
h̞̭̀e̵̦̠̪̘̗'̨l͎͖͇̩̻̮̟͞l̷͕̤̗̪̯ͅ ̨͇̥͚̗c̵̥͕̙͔͚͖͎ó̥m͘e̟͚͓̝̖͇͔͞ ̝f̢̗̝̖̫̦͕͇o̞̱̙r̗͎͓̻ ̛̝͉̺̮̦͔͔ý͍͓̺̣ó͙̠̤̝̩u̖̮̫͟!̤̹̟̬͞
